export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const SHOW_STREAMS = 'SHOW_STREAMS';
export const HIDE_STREAMS = 'HIDE_STREAMS';
export const SELECT_STREAM = 'SELECT_STREAM';

export const FETCH_STREAMS_REQUEST = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_FAILURE = 'FETCH_STREAMS_FAILURE';
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS';
