export const FETCH_STREAMS_REQUEST = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_FAILURE = 'FETCH_STREAMS_FAILURE';
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS';

export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
