export const FETCH_STREAMS_REQUEST = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_FAILURE = 'FETCH_STREAMS_FAILURE';
export const FETCH_STREAMS_SUCCESS = 'FETCH_STREAMS_SUCCESS';

export const UPDATE_STREAMS_REQUEST = 'UPDATE_STREAMS_REQUEST';
export const UPDATE_STREAMS_FAILURE = 'UPDATE_STREAMS_FAILURE';
export const UPDATE_STREAMS_SUCCESS = 'UPDATE_STREAMS_SUCCESS';
