language: node_js
node_js:
  "6.2.2"
install: npm install
script:
  - npm run build
  - npm run test
addons:
    code_climate:
        repo_token: f014d4250848e3e4e131f2388d220601b8994ecaca4a6624bdbada6761ad6468
