language: node_js
services: docker
sudo: required
node_js: 6.2.2
install: npm install
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  - secure: l9mqMooBAPv0SioSYRTTpNF7rWazKeo+H30Fg3wFygrl4Vi1nBle4RM7/s6nhOnlv64W5m6TrKw/Nu0XQ2aPzwrbjUVYs92srHy7bjs7JJJ8EprvOFORCmQtw2yRPUX3pE0SfCzZZLGD2IyZ9arZNkV5YMY5kVyXuzMpWeGzAGDv3J6gURx3PDSzkRUnkGijSryqcN1vxikOCpJ/wXs/nGRyNpgBU0r5ej4flvT/BuaVx8R/yVoUKOtDzh2zG9cqVMjUDRsVaBeXpgaTsLIdgGp0VeOxpHQumYp+64x4iaw+ykNKi3orev25J07IddR+T6jh9JYBj4nBBzuCpL8HOFB8IodFTojJz4kogny5n6J3O7ZEci/ahjAH3+0hmIGn+9ZHE97wGoRNhNIJ4+JdMn15DuSZ0kJE5qbekqatQkATe/Zt80zvne4+TNXJ9p+CRsM2CEVAUbxRk1V8lgYaKBytI568DZmK5mpJ7ndr4bdbDnblMlFqGVIZ8bmIh/T4NPJWtmPKmmBac4j26CiATiNbTWXQh+LVyJpJjT90XlNgc3BnGQE9Mvbu8d/qwLkTtf21MKlkJfzFLvR2TnSlsBQuHAwV+smKE8o6ymB/hwO2QRW/OH006rLfqx2YS88q7mm8FJNvbA3kapzrH9zfEz4PRuJNSuAWbZ9QFsCQkRg=
  - secure: c2jOR/mF6TOfVSl9z8BNh+M0g9kq7VKIY6EFVTR0Wki43twSGa1bYV/GIeAgz65CfD8DPjdIH3zFoRElOxkZ+dzqOTThvacLJ5DUcw4C2HwphUBCPYHl6E/YO6a6QHYFNEc24fJlWWVxqQThiJgMairNO1SRfBbbCW7lrieikz3s2jUmeNIjlLFpMO9YzfdwLfsj1wL0tb98owyxcULW9Ir2XLmfS0OwY/64jfQX34FHujv/H/NOfFWm+SrFB9sZfqlXbaA67ndTyg6ekr8xTZpThgTyGoGfV7c9X6AJzQyPv4uerQ7rFUPCHcKOA8JZxbSZhYJohKh2DuKXhAs/7uA7t6vm8n4Cn8tajmWW4ckVlUyE6Rz1PqnW6TTEeFxZ99g3+NmtM28Iy/QDuifYEvJItChYAdlFsrH/sn9LcYAJDwOew/mX+lxUqUIdQf+Llui0EQl0UHoNbZoC97FTcc9ZOyBkNPNlSPflVLx12D52mNPhFy8fp1dfs/pQv+RqzAOzmRi99B921pJUCrbzvj5HXdDvcI+/q0XSlGbrjwFa3Fv441If2BXclDaVK3s7b9NamEAThJrPfxveubQQn7zhKUSppBzjWJ/SUlLLEzxoMZsr+SLJXxvM/h1BVhAtZZ305j7zEuSXuANmygSuyNi2V6XPMxgN9WP6SlSwguM=
  - secure: euMxRSrP0pEGZcVRhozgFhSw4PilKw7ihmOsUAM0owh2imSHR8KRAcegn7h3cSKW50OtEELzgVaZR/Hu+r9JwZLUG5SpY5vO5Dl2XcVc5LWP9/rEypDBHdFBdnEKIZdF2ik2evMZ8+PSWbn09y4zEyHSE31NZf0hIjmvB03432Qz787vZOV3QsdTKcNtlSmX78sDs3p7AQN4ZSfMkrCfOKyQdrHyw69QSInKNveUPk/uyqoLZXyIMYEmLqjH4O87rjpBbycKEuqNI1Dr3jOc0PokeONvC7enopIsb+1kIKhvnAPnBr65WlLjpj/9rABH4de+myRo5rNBslwzfIdtC0iXINRUrLBnKSUxfYIprlEOzQ/o+vv7apB7AwB21AGHdmrG6dOwJowOgvQkwtUScySh4ajin/flFIL3HqpPNnq3MY/FdFxmEuuqlOkpQxtG7ufaTCqmVwqUclnL8cloYAYU2KuqPE+8qJPtA/3eJn35aIRVC8+D5uo2om/VACIYrG3CGw7BMIC33Dibx9pWCHcpd2hrgZDUK4PAE3ANosX2EqfNOIfsbug0PZONs2zULtLIUEpYFNdd671p7wR6urN0YbQkqDLyiXf27MePnVPhAQnCFShT3jBVi5fv7k45j8P9Vs9pd9YnLg6/OZW+cKkjyFhgmdvw4ThwuwQcXOo=
before_script: npm install -g codeclimate-test-reporter
script:
- npm run build
- npm run test
after_script: codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=$DOCKER_USER/k-auth
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
addons:
  code_climate:
    repo_token: f014d4250848e3e4e131f2388d220601b8994ecaca4a6624bdbada6761ad6468
