language: node_js
node_js:
  "6.2.2"
install: npm install
before_script: npm install -g codeclimate-test-reporter
script:
  - npm run build
  - npm run test
after_script: codeclimate-test-reporter < ./coverage/PhantomJS 2.1.1 (Windows 7 0.0.0)/lcov.info
addons:
    code_climate:
        repo_token: f014d4250848e3e4e131f2388d220601b8994ecaca4a6624bdbada6761ad6468
