language: node_js
services: docker
sudo: required
node_js: 6.2.2
install: npm install
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  - secure: kR2MTzJOX2ZWROipFgZtGNIQgDl0WPDqGP2awJvGfpdcoQslxh0M68faRNWuxmA6kyBwzk0Y3wSazDR9iiNVJB66j3EJrJn5Sv5GF/apsfvhl6nlMMTPDS7z5OatqlBdAJsPPX36LfgCKj5U3yJ5TJ+VlfLIzfjNTQ/hyyGmDnoFJAeBZpd377BPcMpTDjTGlaydSTd5uM+08kJepM9P4zvQlnvfyyQYgM7OUq0A+bavn9hwc0W97op/Rntct4bEzWS1+5yuvG+DIB8laC1Oqd4WqDb12IxLMHYFyJ29U8ux7rOHge98i4r9WaFmhZerft/ZD22hy4tz+J1HkMLtID4zQDTT4O0PWGVNVgwqZMH4B0owSgW159Yg36d0+pKizWcSDkOyyQXYfignHI190tD67PvXVhz/oih/vTM9R58eHK+4kRcMwh8ffe+XIvqZPjPeRyoKTlpGUfzZ0J76iAZ57BCtJPeIqpqbEPJttANQXoMTula44fDw5xWTvbs2BYp7IfXsSfmvsnOimLHKPlHREblm5swAxR9TAodzWCabV34KgYcO9xQv6/sUeo1gt5yjRDY7ZJTXR8hFz7SyD/ZWrGKg8tL17szwxvKMrlTQyjrdAk9hJqygZX+OoGpsg0It3f3xIXzbPL28UHSOJfv84iTTBLgKw8Lo5Ewc80k=
  - secure: GdKZoS3TsJsZStPYWsI/wiF7CyUsfS3l27s5YNr15UgNY92Aq0emqqyG7Yh6GmwymRlu0bRumVY1zn0+HMMWaG2yGBpEE5C0aoIq2zbqgOt26oP7IBrhqAfnDpm6sf/B6SDqxTNjZRVJQifTs1up7SBbL/QbOKB1lqWRk0E0LkTVSkvEML2Y5meGjnVdQ9T4WHxzoEh7Jk8Jbn62ysptb4yZKCDOn1EV1m/ogddDJNiOSplSHncB0qh/PK/VIKHI87YiPXn7BdNXwgwdZeqsPuyoSJuHEWSblbc/ZJCa/jzLFpn8CmApo85sRZ40oeF07aZXrLeUypgO3jXfn9ORhhLmdIviXvvDLXhD/G7cdzTh7H8yKGEAek0xlNZ1VM1iZsZpCjwJ5flgTagrsr08uvmb5u3vEUWY3T01gpY4/YSfp5Cb/OLGrADRT3CUoK892FvgAgxBHQ9LXLeBI5Jm5kouDEbHji1SYjq21POsD1Y6k1bp4O6onIaI7LzVZ48HFnW6acc3UaQ/7u5qUQInoQUQFAkNqUG8Ywy/Lp03caLQWImKE8mX/hxUdWlOP288KR0SppiffgJVrUJetnJPaWRy9ReEzvxpQ8ap039ZP8B7e7ept626ixsWewuAvOfFPn0dg4whGgsd/FgpEOj/RiSA7MV5TjWu8XGpp7x686Q=
  - secure: IhqZcjKJ+1sMtd1paDu26iGwFsC0+tXVC5mea0qxQs0mle/VC7Lrmgmqg7aMPNg7pNi/4Vha8xd9f+wbJlfyDLa3HYDUghOkMIL7wBMeZ27a1oW9GwNH25SM00t1//h8iFy9xU+cm9Q5tJAXg2tkWmeD6p1JGkmK+CQICh5d4Vo48iNLysEBLGWu4+L1Ak+GZhXIZ1OcZidU4ukkwWbL1AVbUGzkuMEmnvx8PIPsTycBC+y8EcpwovZ1tAzBow4TyBOrRTYvvZ/ahv0kViku18wrRk168IA+LyrpMLgVAWKuhzXaXijoSEJDDT8axoxCOYVgbZ71rcYmzRK7M9JGI8xHqOxpSiGfDf8T7XGX3VSGBm8OhPoHqlSy3uzgE1qRg0KOuuzjIk5pxjhtg555fIa00q1DTYGXbnt4y5qvx4fj3DHkXu/DqqCRkotVz1Vw5TyFecFfeGXEBumylLN4AX+qwkf1u+EhPLhbsKuNyFAQnx48taVanBPygO8i+ddt3dOgzFOVsChkuKzp/lptNebVtPyKbQaAwjLv5iF+8oAoDedrM80XOTlOQTKwrOzuRhTwrksue4BsYsno7F2K12zcHssAiqo13T6K+ueb4nzGW1Vy0Mr928v+14v0WKyDreIgt5CBEOr1YVAaoxhSrgXmg9Oq3RsSKkEMNJKKWwc=
before_script: npm install -g codeclimate-test-reporter
script:
- npm run build
- npm run test
after_script: codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASS"
- export REPO=$DOCKER_USERNAME/twitchwatcher-react
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- echo $REPO:$TAG:$COMMIT
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
addons:
  code_climate:
    repo_token: f014d4250848e3e4e131f2388d220601b8994ecaca4a6624bdbada6761ad6468
